DEFINE
	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Calendar'[Month N],
			'Calendar'[Month No],
			"Total_Sales", 'Measures Table'[Total Sales],
			"Sales_Highlight", IGNORE('Measures Table'[Sales Highlight])
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(1001, __DS0Core, 'Calendar'[Month No], 1, 'Calendar'[Month N], 1)

EVALUATE
	ROW(
	"Sales_Subtitle", 'Measures Table'[Sales Subtitle]
)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'Calendar'[Month No], 'Calendar'[Month N]